### ISSUE TITLE
adding orac packages?

### ISSUE THREAD

**Issue by TheTechnobear** [BlokasLabs/patchbox-modules#1]
where do I add the actually debian packages?

can you upload please?

https://www.dropbox.com/s/2jsniwr9yx34fxq/orac_pbox.tgz?dl=0

**Comment by gtrainavicius** [comment]
You have to send (or link) them to us, uploading to blokas apt is separate process from GitHub, I'll upload the packages right now. :)

**Comment by TheTechnobear** [comment]
ok, but I think this needs to be 'connected'

I dont want to have to start editing this repo, sending pull requests,  then having also having to upload to dropbox, and send a link.... 

what I think perhaps would be better is
have a repo (*) which contains this AND the packages, that 3rd parties can fork and send PRs too.
then you accept the PR there, and have a script that then stages the package on the apt-server and updates this repo. 


(*) Im assuming this repo cannot be used, as its the one in use by patchbox clients.


another alternative, id be happy is...
is to prepare a package thats put on patchstorage, that you then  take on to you apt-server.


what I want to really avoid, is having to update things in multiple places, thats how things get missed, and things go wrong ;)

**Comment by gtrainavicius** [comment]
I have uploaded the new debs to staging area. Just changed the ORAC version locally in [patchbox-module.json](https://github.com/BlokasLabs/patchbox-modules/blob/master/orac/patchbox-module.json#L3) to v1.0.1, tried running the update via `patchbox` and activating ORAC, everything went fine.

Should I put the new packages to the public /apt/ now?

As for the update release procedure, we can refine this as we go along, we plan to add support of just pasting a patchstorage link to the `patchbox` config tool, so hosting the modules on patchstorage may be the way to go, we'll see. :)

**Comment by TheTechnobear** [comment]
cool, thank you 
yup all ready to go - so be great if you can make public.

yeah, I totally recognise this is all new, so can be refined as you move forward.

I think generally if you want others something simple is important, as you may find that some that want to contribute are not developers.
also if its successful, then you (blokas) will not want to have to do too much support/hand holding etc 

(this is something we found with axoloti - really its best to let contributors do it themselves as much as possible)

**Comment by gtrainavicius** [comment]
Ok, done, it's now in public apt and patchbox-module.json version updated.
